### ISSUE TITLE
Max-Cut example minimizes the objective function instead of maximizing it

### ISSUE THREAD

**Issue by paob** [peterwittek/ncpol2sdpa#1]
Hi Peter,

I found your library while looking for implementations of the SOS/Lasserre hierarchy and I'm having a lot of fun using it. Amazing work here!

I noticed that the Max-Cut example that you ported from Gloptipoly seems to be incorrect.

If I understand correctly, the objective function has to be provided in minimization form, right? If so, then I guess you just need to multiply by -1 the objective function and then the optimal value when it is returned.

Also, would it be possible to automatically add the ignored constant term in the objective function to the primal and dual values as a result of `solve_sdp`?

Thanks a lot for your work,
Paul

**Comment by peterwittek** [comment]
Thanks for your comments.

The constant term is not added by design because this way you get the exact same result when you solve the problem with SDPA or Mosek, export it to a dat-s file and solve it with SeDuMi, or convert it to PICOS.

The max-cut objective function should indeed get a negative sign. If we do that, the value is -4.5. I have to verify if this is correct. I can only do that tomorrow.

**Comment by paob** [comment]
Thanks a lot!

Indeed I could replicate an optimal value f\* = -4.5 and after adding the missing constant term -9 I got: -(f\* - 9) = 13.5 which looks pretty good.

Thank you for your fast reply,
Paul

**Comment by peterwittek** [comment]
Hi Paul,

I corrected the objective function and also rewrote a few lines in the example to make it more Pythonesque. Thanks again for your comments.

Peter
