### ISSUE TITLE
ncpol2sdpa silently fails on sdpa errors

### ISSUE THREAD

**Issue by kalmarek** [peterwittek/ncpol2sdpa#28]
I had problem with my local sdpa installation (it was linked to mpi-enabled mumps, but I think it doesn't matter);
command for sdpa as of https://github.com/peterwittek/ncpol2sdpa/blob/master/ncpol2sdpa/sdpa_utils.py#L148 was a valid command but `tmp_out_file` contained only 

```
SDPA (Version 7.3.8) start at [Wed Aug  3 15:31:37 2016]
set   is DEFAULT
data  is /tmp/kalmar/tmph1_j3o8j.dat-s : sparse
out   is /tmp/kalmar/tmph1_j3o8j.out
NumThreads  is set as 1
```

hence all line.find in https://github.com/peterwittek/ncpol2sdpa/blob/master/ncpol2sdpa/sdpa_utils.py#L64-L82 evaluated to false and primal, dual, etc remained undefined;

sdpa run by hand returned (in addition to the above):

```
*** The MPI_Comm_f2c() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
Abort before MPI_INIT completed successfully; not able to guarantee that all other processes were killed!
```

I don't know if this is intentional, but the loop (https://github.com/peterwittek/ncpol2sdpa/blob/master/ncpol2sdpa/sdpa_utils.py#L64) should have some check for empty/invalid solution??

I'd be happy to do this, but You'd have to instruct me on how You'd like to be done (or just point me to an example); The check can be implemented in `sdpa_utils.read_sdpa_out` (better??) or just in `sdpa_utils.solve_with_sdpa`, e.g. using `try: subprocess.check_call` (instead of `call`) and catching `CalledProcessError` should sdpa fail.

**Comment by peterwittek** [comment]
I think SDPA will always produce an output file if the command line call is correct. So perhaps it is worth focusing on validating the output file before reading it. I did not implement it because if you instantiate the SdpRelaxation object with verbosity level >0, you would see the output in the Python console.

It would be wonderful if you could do this file validation. I reckon the simplest solution is to do this check in read_sdpa_out, and if the file is invalid, then the status string can be set to "invalid", return dummy values for the optimum and solution matrices. Please keep in mind that the output file can grow to several gigabytes, so we have to decide its validity in the single pass we do over it.

Please check the output files for SDPA-GMP. It might be slightly different, but it is essential in certain problems to have arbitrary-precision solutions.

**Comment by kalmarek** [comment]
I had a look at [SDPA manual](https://sourceforge.net/projects/sdpa/files/sdpa/sdpa.7.1.1.manual.20080618.pdf) looking for the specification of the output file; I could only find described example;

I think right now, that if we trust functions that parse solution matrices (parse_solution_matrix from sdpa_utils) then we need only to check that variables `status_string`, `primal`, `dual`, and (if asked for `solutionmatrix`) `x_mat` and `y_mat` are defined after the pass over the output file.

This should be easy enough with 
`try - except NameError - else`

However, if suspect that the output file may be subtly corrupt (e.g. in the middle of the solution matrix), then more modification to parsing function is required. btw. how well does python handle growing `x_mat` into multi-GB range?

Also: what should be the dummy values set for the case status_string = 'invalid'?
np.nan's? e.g. x_mat=np.array([[np.nan]])?

**Comment by peterwittek** [comment]
`parse_solution_matrix` is pretty inefficient -- don't expect the text parsing efficiency of pandas, but it works for large files. If the file is large, that means that solving the problem takes magnitudes longer than parsing the result, so that is fine.

Now that you mention `NameError`, I realize that the implicit assumption in `read_sdpa_out` is that all of the variables are defined. This can fail between l85 and l88 if the output file is corrupted and the function is called internally from the SdpRelaxation class, which is the typical use case.

I suggest to keep it simple. Let us set `primal`, `dual`, `x_mat`, `y_mat`, `status_string` to `None` at the beginning of the function, and if any of them are none after parsing, set status_string to invalid. It really should be up to the user to check the status before using the results.

**Comment by peterwittek** [comment]
Commit 2127e52a4471c5ee33b67c5cc91839acbd7d7b51 resolves it.
