### ISSUE TITLE
Probability function

### ISSUE THREAD

**Issue by anubhav70747** [peterwittek/ncpol2sdpa#34]
the Probability function does not work for more than 2 inputs. For instance, if one declares a single party quadruple input out scenario,
P=Probability([4,4])

Then P.get_all_operators() returns,
[A00, A01, A02, A10, A11, A12]

which means that it fails to declare more than 2 measurement settings, while it is able to declare more than 2 projectors per measurement
Furthermore, P([0],[2]) returns,
Exception: Invalid measurement index 2 for party A

**Comment by peterwittek** [comment]
The behaviour is correct. If you look at the parties, you get this:

```python
>>> P.parties
[[[A00, A01, A02], [A10, A11, A12]]]
```
You requested two four-output measurements, and you get three matching operators. The last one is left out because it is assumed that you work in the Collins-Gisin picture. This way the SDPs you generate can exclude the sum-to-identity constraint and save lots of redundant monomials.

The notation for a single-party conditional probability is p(a|x). Since you have two measurements, x can only take the value 0 or 1.
