### ISSUE TITLE
[Feature request] DSOS and SDSOS hierarchy 

### ISSUE THREAD

**Issue by htadashi** [peterwittek/ncpol2sdpa#39]
Hi Peter! 

Thanks for developing ncpol2sdpa and sharing it with the community. It is great to have a polynomial optimization library available in a free software.  
Do you have any plan to add [DSOS and SDSOS hierarchy](https://arxiv.org/abs/1706.02586) for polynomials with commuting variables on ncpol2sdpa?

**Comment by peterwittek** [comment]
Thanks. It comes timely: we are having a discussion tomorrow about the future of Ncpol2sdpa and other SDP hierarchy generators.

Note, however, that Ncpol2sdpa is no longer developed on GitHub due to organization's recent acquisition. The new home is on [GitLab](https://gitlab.com/peterwittek/ncpol2sdpa). I would like to ask you to continue the discussion there. Because of this, I am closing the issue here.
