### ISSUE TITLE
adding constant to the function being optimized has no effect

### ISSUE THREAD

**Issue by sashasami03** [peterwittek/ncpol2sdpa#5]
In the matrix 'I'   (  in the example CHSH_{1+AB}.py  )    changing I[0][0] that is the constant of target function being optimized does not change the optimal value. I am using  cvxopt as the solver ( by using the function convert_to_picos() ) . Are constants in the objective/target function not considered while outputting  the optimal value of the target function being optimized ?
Also cvxopt seems to return the absolute of the optimum value. I tried the example here  'http://peterwittek.com/quantum-bound-on-the-chsh-inequality-using-sdp.html'  but even multiplying the objective by -1 ( or not ) gives same optimal value for objective function 2.828 and not -2.828 and 2.828.

**Comment by peterwittek** [comment]
This is a subtle issue and it has been the source of much confusion. Both Mosek and CVXOPT flip the sign of the objective function sometimes -- it seems that with the generated SDPs they always do this (@cgogolin). Furthermore, none of the solvers -- SDPA, Mosek, and CVXOPT -- accept constant terms in the objective function. To keep results consistent when using the solve_sdp function and when solving a problem externally, the sign flips and the discard of the constant term were ignored. If you set verbosity level above zero, you get a warning of the constant term if there is one.

Since most users won't bother with solving an SDP externally, I just pushed a commit that takes care of the sign flips and the constant terms when using solve_sdp. Note that this does not change the behaviour of the PICOS converter or the export functions: those will still disregard constant terms, this is entirely external to Ncpol2sdpa. 

You can try the new behaviour with the latest git and calling `solve_sdp` with the option `solver='cvxopt'`.

**Comment by peterwittek** [comment]
The updated behaviour of `solve_sdp` has been tested reasonably well with all solvers, so I am closing this issue.
